import { useNavigate, useParams, useLocation } from 'react-router-dom'
import { Download, ChevronLeft, FileText, Users, BookOpen, MessageSquare, ArrowRight, Zap } from 'lucide-react'
import dayjs from 'dayjs'

// Mock AI report — will be generated by Lambda + Bedrock Nova Lite
const MOCK_REPORT = {
  topics: ['Introduction to Periodic Table', 'Element groups and periods', 'Atomic number and mass', 'Valence electrons and bonding basics'],
  participationSummary: 'Session had 30 participants. 24 remained consistently active throughout. 6 participants showed reduced engagement after the 20-minute mark.',
  notableQuestions: [
    'Why do noble gases not react with other elements?',
    'How is atomic mass different from atomic number?',
    'Can an element exist in multiple groups?'
  ],
  followUpActions: [
    'Share the Periodic Table reference sheet with all participants',
    'Schedule a quiz for next session on element groups',
    'Follow up with 6 participants who disengaged — consider shorter segments'
  ],
  attentionAvg: 84,
  duration: '42 minutes',
}

function Section({ icon, title, children }) {
  return (
    <div className="report-section">
      <div style={{ display: 'flex', alignItems: 'center', gap: 10, marginBottom: 16 }}>
        <span style={{ color: 'var(--accent-blue)' }}>{icon}</span>
        <h3 style={{ fontSize: 14, fontWeight: 600, color: 'var(--text-secondary)', textTransform: 'uppercase', letterSpacing: '0.05em' }}>{title}</h3>
      </div>
      {children}
    </div>
  )
}

export default function ReportPage() {
  const { sessionId } = useParams()
  const location = useLocation()
  const navigate = useNavigate()
  const state = location.state || {}

  const report = MOCK_REPORT
  const roomName = state.roomName || `Session ${sessionId}`
  const now = dayjs().format('DD MMM YYYY, h:mm A')

  return (
    <div className="page" style={{ minHeight: '100vh' }}>
      {/* Nav */}
      <nav className="nav">
        <div style={{ display: 'flex', alignItems: 'center', gap: 12 }}>
          <button className="btn btn-ghost" style={{ padding: '6px 10px', fontSize: 13 }} onClick={() => navigate('/cockpit')}>
            <ChevronLeft size={14} /> Cockpit
          </button>
          <span className="nav-logo" style={{ fontSize: 16 }}>◎ Halo</span>
          <div className="badge badge-purple">AI Report</div>
        </div>
        <div style={{ display: 'flex', gap: 10 }}>
          <button className="btn btn-ghost" style={{ fontSize: 13 }}>
            <Download size={14} /> Download PDF
          </button>
        </div>
      </nav>

      <div style={{ maxWidth: 760, margin: '0 auto', padding: '88px 24px 64px', position: 'relative', zIndex: 1 }}>
        {/* Header */}
        <div className="fade-in" style={{ marginBottom: 32 }}>
          <div style={{ display: 'flex', alignItems: 'center', gap: 8, marginBottom: 12 }}>
            <div className="badge badge-purple" style={{ gap: 6 }}>
              <Zap size={10} /> AI Generated
            </div>
            <div className="badge" style={{ background: 'rgba(255,255,255,0.04)', color: 'var(--text-muted)', fontSize: 11 }}>
              {now}
            </div>
          </div>
          <h1 style={{
            fontFamily: 'var(--font-display)',
            fontSize: 32,
            fontWeight: 700,
            letterSpacing: '-0.02em',
            color: 'var(--text-primary)',
            marginBottom: 8
          }}>
            {roomName}
          </h1>
          <p style={{ fontSize: 14, color: 'var(--text-muted)' }}>
            Post-session AI report · Session ID: {sessionId} · Duration: {report.duration}
          </p>
        </div>

        {/* At-a-glance */}
        <div style={{ display: 'flex', gap: 12, marginBottom: 24, flexWrap: 'wrap' }} className="stagger">
          {[
            { label: 'Avg Attention', value: `${report.attentionAvg}%`, color: 'var(--status-green)' },
            { label: 'Topics Covered', value: report.topics.length, color: 'var(--accent-blue)' },
            { label: 'Notable Q&As', value: report.notableQuestions.length, color: 'var(--accent-purple)' },
            { label: 'Follow-ups', value: report.followUpActions.length, color: 'var(--status-amber)' },
          ].map(stat => (
            <div key={stat.label} className="glass-card" style={{ padding: '16px 20px', flex: '1 0 140px' }}>
              <div style={{ fontSize: 11, color: 'var(--text-muted)', textTransform: 'uppercase', letterSpacing: '0.06em', marginBottom: 6 }}>{stat.label}</div>
              <div style={{ fontSize: 26, fontWeight: 700, fontFamily: 'var(--font-display)', color: stat.color }}>{stat.value}</div>
            </div>
          ))}
        </div>

        <div className="stagger">
          {/* Topics covered */}
          <Section icon={<BookOpen size={16} />} title="Topics Covered">
            <div style={{ display: 'flex', flexDirection: 'column', gap: 8 }}>
              {report.topics.map((t, i) => (
                <div key={i} style={{ display: 'flex', gap: 10, alignItems: 'flex-start', fontSize: 14, color: 'var(--text-secondary)' }}>
                  <ArrowRight size={14} style={{ flexShrink: 0, marginTop: 3, color: 'var(--accent-blue)' }} />
                  {t}
                </div>
              ))}
            </div>
          </Section>

          {/* Participation summary */}
          <Section icon={<Users size={16} />} title="Participation Summary">
            <p style={{ fontSize: 14, color: 'var(--text-secondary)', lineHeight: 1.7 }}>{report.participationSummary}</p>
            <div style={{ marginTop: 12 }}>
              <div style={{ display: 'flex', justifyContent: 'space-between', fontSize: 12, color: 'var(--text-muted)', marginBottom: 6 }}>
                <span>Session attention</span>
                <span>{report.attentionAvg}%</span>
              </div>
              <div className="attention-bar" style={{ height: 6 }}>
                <div className="attention-fill high" style={{ width: `${report.attentionAvg}%` }} />
              </div>
            </div>
          </Section>

          {/* Notable questions */}
          <Section icon={<MessageSquare size={16} />} title="Notable Questions">
            <div style={{ display: 'flex', flexDirection: 'column', gap: 10 }}>
              {report.notableQuestions.map((q, i) => (
                <div key={i} style={{
                  padding: '10px 14px',
                  background: 'rgba(139, 92, 246, 0.07)',
                  border: '1px solid rgba(139,92,246,0.15)',
                  borderRadius: 'var(--radius-sm)',
                  fontSize: 14,
                  color: 'var(--text-secondary)',
                  lineHeight: 1.5
                }}>
                  "{q}"
                </div>
              ))}
            </div>
          </Section>

          {/* Follow-ups */}
          <Section icon={<FileText size={16} />} title="Suggested Follow-up Actions">
            <div style={{ display: 'flex', flexDirection: 'column', gap: 8 }}>
              {report.followUpActions.map((a, i) => (
                <div key={i} style={{ display: 'flex', gap: 10, alignItems: 'flex-start', fontSize: 14, color: 'var(--text-secondary)' }}>
                  <div style={{
                    width: 20, height: 20, borderRadius: '50%',
                    background: 'rgba(59,130,246,0.1)',
                    border: '1px solid rgba(59,130,246,0.2)',
                    display: 'flex', alignItems: 'center', justifyContent: 'center',
                    flexShrink: 0,
                    fontSize: 11, fontWeight: 600, color: 'var(--accent-blue)'
                  }}>
                    {i + 1}
                  </div>
                  {a}
                </div>
              ))}
            </div>
          </Section>
        </div>

        <div style={{ textAlign: 'center', marginTop: 32, fontSize: 12, color: 'var(--text-muted)' }}>
          Report generated by Halo AI · Powered by Amazon Bedrock Nova Lite
        </div>
      </div>
    </div>
  )
}
