import { X, Zap, ArrowRight } from 'lucide-react'

// Mock summary — in production: fetched from Lambda → Bedrock Nova Lite reading S3 transcript chunks
const MOCK_SUMMARY = [
  'Session opened with an overview of the Periodic Table structure and history.',
  'Discussed element groups: alkali metals, halogens, and noble gases in detail.',
  'Explored atomic number vs atomic mass — common exam question highlighted.',
  'Explained valence electrons and their role in chemical bonding.',
  'Teacher answered 3 notable questions; quiz scheduled for Thursday.',
]

export default function AISummaryCard({ roomName, onDismiss }) {
  return (
    <>
      {/* Backdrop */}
      <div className="modal-backdrop" onClick={onDismiss} />

      {/* Card */}
      <div className="ai-summary-card">
        <div style={{ display: 'flex', alignItems: 'flex-start', justifyContent: 'space-between', marginBottom: 20 }}>
          <div>
            <div className="badge badge-purple" style={{ marginBottom: 10, gap: 6 }}>
              <Zap size={10} /> AI Late Joiner Summary
            </div>
            <h2 style={{ fontSize: 18, fontWeight: 700, color: 'var(--text-primary)', lineHeight: 1.3 }}>
              Here's what you missed
            </h2>
            <p style={{ fontSize: 13, color: 'var(--text-muted)', marginTop: 4 }}>{roomName}</p>
          </div>
          <button
            onClick={onDismiss}
            style={{ background: 'none', border: 'none', cursor: 'pointer', color: 'var(--text-muted)', padding: 4, flexShrink: 0 }}
          >
            <X size={18} />
          </button>
        </div>

        <div style={{ display: 'flex', flexDirection: 'column', gap: 10, marginBottom: 24 }}>
          {MOCK_SUMMARY.map((point, i) => (
            <div key={i} style={{ display: 'flex', gap: 10, alignItems: 'flex-start' }}>
              <div style={{
                width: 22, height: 22, borderRadius: '50%',
                background: 'rgba(139,92,246,0.12)',
                border: '1px solid rgba(139,92,246,0.25)',
                display: 'flex', alignItems: 'center', justifyContent: 'center',
                flexShrink: 0, fontSize: 11, fontWeight: 700, color: 'var(--accent-purple)'
              }}>
                {i + 1}
              </div>
              <p style={{ fontSize: 14, color: 'var(--text-secondary)', lineHeight: 1.6 }}>{point}</p>
            </div>
          ))}
        </div>

        <div style={{ display: 'flex', gap: 10 }}>
          <button className="btn btn-primary" style={{ flex: 1, justifyContent: 'center' }} onClick={onDismiss}>
            Got it — join session <ArrowRight size={14} />
          </button>
        </div>

        <p style={{ fontSize: 11, color: 'var(--text-muted)', textAlign: 'center', marginTop: 12 }}>
          Generated by Amazon Bedrock Nova Lite · Shown once per join
        </p>
      </div>
    </>
  )
}
